### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by alnutile** [LaraChat/live#3]
Read recently about Wordpress and Laravel integration. Just wondering the different requirements for a CMS and when Laravel is a good fit and when it is not and we need Wordpress or Drupal etc

**Comment by mikebronner** [comment]
Hi @alnutile, funy you should mention this. I have been talking with others about this topic as well. Right now I am working on creating an end-to-end workflow for the following (and will be making a comprehensive write-up):

### Phase 1:
- Installing Wordpress Core, Plugins, and Themes using composer (nothing new)
- Building themes and child themes using Elixir

### Phase 2:
- Use Wordpress core (no plugins or themes) as backend content admin only
- Create Laravel app (using Wordpress-Laravel bridge) as the front-end app.

### Phase 3:
- Create admin package to replace Wordpress as a backend tool, allow packages to drop in and extend it.

I am completing phase 1 today (for one project), and will be working on Phase 2 the week after next (for another project). I think this ties very well into the discussion of moving to creating drop-in packages for Laravel, instead of stand-alone apps. What Laravel needs is a core admin panel that packages can be dropped into, like Wordpress admin (phase 3).

This is certainly an interesting and multi-faceted topic!

**Comment by tutelagesystems** [comment]
I have been working on one for work, however I cannot share any of the true code as it isn't open source... in the end I don't even own it technically ;)

The thing with the way that we have to do it at work isn't a real "CMS" it is used more for our other developers develop an application and it can go into this application and it allows us to assign permissions to a user so they can access the application and what permissions they can do inside of it.

Basically the way I have done it is using a Service Provider that will loop through any installed modules (and looking at that code now, should also check for enabled) and for each one it will load the routes up and the views.

Everything else because of namespacing works (models, etc)... Anyway I can share the Service Provider as I found the idea on the web already, just with some modifications

```
<?php namespace App\Modules;

class ServiceProvider extends  \Illuminate\Support\ServiceProvider
{

    public function boot()
    {
        // check to see if the module table exists
        $results = \DB::select("SHOW TABLES like 'modules'");

        if(count($results) <= 0)
        {
            return;
        }

        // find all modules where they are installed
        $modules = \App\Module::where('installed', true)->get();
        // $modules = \App\Module::all();

        foreach($modules as $module)
        {
            // load routes
            if(file_exists(__DIR__ .'/'. $module->class_name .'/routes.php')) {
                include __DIR__ .'/'. $module->class_name .'/routes.php';
            }

            // load views
            if(is_dir(__DIR__ .'/'. $module->class_name .'/Views')) {
                $this->loadViewsFrom(__DIR__ .'/'. $module->class_name.'/Views', $module->class_name);
            }
        }
    }

    public function register(){}

}
```

Not sure if this is helpful to anyone but it could help in creating such a system where you can drop in modules / applications.
