### ISSUE TITLE
Episode 19 - LaraChat Live (January 19th, 2017)

### ISSUE THREAD

**Issue by smayzes** [LaraChat/live#7]
Hosts
****
@mlantz
@ericvanjohnson
@smayzes
You?

**Guests**

@jeffreyway

**Topics**

**Comment by JeffreyWay** [comment]
Hey, folks. Potential topics:

- Laravel Mix (what is it, why does it exist)
- Framework hate in the PHP community
- Testing ecosystem
- Laravel with SPAs... what does that look like.

**Comment by ericvanjohnson** [comment]
What is your recommendation to someone about "How to Learn" or "How to learn to use what you learn" .. I have a problem where every time I see a new technic, I want to apply it to everything I am working on. Any recommendations on how to best apply new knowledge..

**Comment by mlantz** [comment]
Framework hate? Do we mean people's insane obsession with trying to decouple things etc etc? I'd LOVE to talk about that! and that brings a handful of questions to mind!

**Comment by mlantz** [comment]
Laravel and SPAs is also a great topic of conversation given Taylor's mention of Laravel focusing on a full stack solution going forward.

**Comment by rizqidjamaluddin** [comment]
Damn I would love to pitch into the framework hate topic. But it's another day for me out of town...

I'll think of questions and drop them here.

@JeffreyWay one huge sentiment I'm hearing from the community about you is regarding screencasts and teaching in general. A lot of people want to start livecoding or recording casts; do you think there's a future for livecoding? Should it be done as a full-time effort? Is it comparable to blogging? Should all active developers start recording their thoughts in video form?

**Comment by nealio82** [comment]
I don't think decoupling is 'framework hate'. Some effort put into decoupling makes upgrading the framework around your model far, far easier later on. A colleague of mine had to upgrade a site from Laravel 3 to Laravel 4. Because all the logic was in the controllers, and because the code was liberally sprinkled with helper methods which coupled the system tightly to the implementation, it took him months to get anywhere which should have taken a couple of weeks at most.

To me, Framework hate is the flame wars that exist between users of [insert name of favourite framework here] and [insert name of any other framework here], or those who use no framework and those who won't consider not using one. Remember, a framework is just a tool. You can use it all the time or not at all. It's up to you to learn how to use your tools and how to use them in the most appropriate way (double claw, anyone? https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/).

Anyway, some notes for @JeffreyWay  - As a subscriber to your videos (some of which have helped me greatly), I'd love to see some tutorials on:

1) DDD
2) CQRS & ES
3) Decoupling from Laravel and refactoring existing coupled code to make it portable
4) Architectural planning / engineering 
5) Common approaches to designing domain objects
6) Designing systems with UML

Are there any plans to release video tutorials on any of these subjects?

**Comment by rizqidjamaluddin** [comment]
Oh, one direct question for @JeffreyWay, one I also asked Taylor a few months ago in a different session: is there a video/talk/post you regret making or feel has been misused? Or you think deserve a revisit/revamp? For laravel, this was about the command bus stuff of early 5.x.

**Comment by ericvanjohnson** [comment]
It's 2017 and @JeffreyWay is in Memphis when he orders a Uber. Moments later a Delorean pulls up and JeffreyWay jumps inside. Through a string of wacky events and one spilled big gulp later, JeffreyWay is transported back 50 years to 1967. 

Lyndon Johnson is President of the US, Ronald Reagan is Governor of California, and the Doors released their debut album, however, there is no Taylor Otwell, no Laravel, not even PHP. 

At this time, what does JeffreyWay;

- Do for work to make a living
- Invent  to get his first million dollars
- One book he would write
- One movie he would produce.

**Comment by freekmurze** [comment]
@JeffreyWay I'm curious to know where you learn new stuff.

- What are some good books that you read recently?
- Which podcasts to you listen to regularly?
- Which blogs do you find yourself reading?
- ...

**Comment by Rufflesaurus** [comment]
1. Will Laracasts transform into a Single Page Application anytime soon?
2. Any info on the Database Design Series you mentioned back last year?
3. Will we ever see a `Build a single page application series` with VueJS?
4. Will we ever see a `Build a RESTful API with Lumen / Laravel` series?
5. When learning a new technology / technique / tool / framework, do you learn them as you use them on a throwaway projects or you work on some real projects that will come out someday in the future?

**Comment by mlantz** [comment]
What editor do you use on a regular basis?

**Comment by mlantz** [comment]
lol doh

**Comment by jasonrking** [comment]
A simple one: What direction do you see Laravel going in the next 5 years? And are we all going to be doing good SPA's in the future?

**Comment by codefocus** [comment]
> Laravel and SPAs is also a great topic of conversation given Taylor's mention of Laravel focusing on a full stack solution going forward.

Hooking into that topic, I would love to hear your opinion on what influences your decision on whether or not to implement a project as a Single Page Application.

And whether there is any significant activity in the Laravel community focusing on [AMP](https://www.ampproject.org/).

**Comment by Continuum81** [comment]
The Testingphp book - Is it still a thing ?

**Comment by ericvanjohnson** [comment]
Thanks again to @JeffreyWay for his time last night. Always such a pleasure speaking with you. 

[Video](https://www.youtube.com/watch?v=D2LjhB8hz38)
[Audio Version](http://podcast.larachat.co/19)

Be sure to subscribe to our [Youtube Channel](https://www.youtube.com/channel/UCKAj-eBdBINhJ2Bi9lut29A) to get notifications of future talks
Follow us on Twitter [@larachatslack](https://twitter.com/larachatslack)
And of course join us on the [Larachat Slack Channel](https://larachat.co/)
